# Generated by Django 4.1.6 on 2023-06-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default='', max_length=60)),
                ('password', models.CharField(default='', max_length=60)),
                ('city', models.CharField(default='', max_length=60)),
                ('Balance', models.CharField(default='', max_length=60)),
                ('date', models.CharField(default='', max_length=60)),
                ('time', models.CharField(default='', max_length=60)),
                ('Limit', models.CharField(default='', max_length=60)),
                ('Proffesion', models.CharField(default='', max_length=60)),
                ('Age', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
