# Generated by Django 4.1.6 on 2023-06-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(default='', max_length=60)),
                ('where', models.CharField(default='', max_length=60)),
                ('Why', models.CharField(default='', max_length=60)),
                ('date_day', models.CharField(default='', max_length=60)),
                ('date_month', models.CharField(default='', max_length=60)),
                ('date_year', models.CharField(default='', max_length=60)),
                ('time', models.CharField(default='', max_length=60)),
                ('category', models.CharField(default='', max_length=60)),
                ('wasitneeded', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
