# Generated by Django 4.1.6 on 2023-07-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='userid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
