# Generated by Django 4.2.4 on 2023-11-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0003_expense_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date_day',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date_month',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date_year',
        ),
    ]
